name: Vexpunish
version: 1.0
main: com.vexpunish.PunishmentWebhook
api-version: 1.16
depend:
  - LibertyBans
commands:
  punishmentwebhook:
    description: Comandos do plugin de webhook
    permission: punishmentwebhook.admin
permissions:
  punishmentwebhook.admin:
    description: Permiss√£o para configurar a webhook
    default: op
